
services:
  mysql:
    image: mysql:8
    container_name: padme_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      retries: 5
      timeout: 5s
    networks:
    - liquidation_network

  backend:
    build: ./backend
    container_name: padme_backend
    restart: always
    environment:
      - NODE_ENV=docker
    ports:
      - "7001:5000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend/uploads:/app/uploads
    command: npm start
    networks:
      - liquidation_network

  frontend:
    build: ./frontend
    container_name: padme_frontend
    restart: always
    ports:
      - "4000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    networks:
      - liquidation_network

volumes:
  mysql_data:

networks:
  liquidation_network:
    driver: bridge
